In [9]:
import numpy as np
list_ = [ '1' , '2', '3' , '4' , '5' ]
array_list = np.array(object = list_)
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [11]:
#Q1
# Yes, list_ is a Python list and array_list is a NumPy array.
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)
print(type(list_))
print(type(array_list))


<class 'list'>
<class 'numpy.ndarray'>


In [17]:
#Q2

for item in list_:
  print(type(item))

print(array_list.dtype)


<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<U1


In [19]:
#Q3
# Yes, elements in list_ are strings, while elements in the new arra_list (note the typo in the question, assuming array_list) are integers because of dtype=int.

# Original list_ still has strings
for item in list_:
  print(type(item))

# New array_list has integers
array_list = np.array(object = list_, dtype = int)
print(array_list.dtype)

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
int32


In [21]:
#Q4
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

# (i) shape
print(num_array.shape)
# (ii) size
print(num_array.size)

(2, 3)
6


In [25]:
#Q5
import numpy as np
zeros_array = np.zeros((3, 3))
zeros_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
#Q6
import numpy as np
identity_matrix = np.identity(5)
print(identity_matrix) 


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
